server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size:  80KB

mybatis:
 type-aliases-package: com.imooc.pojo
 mapper-locations: classpath:mapper/*.xml
 configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mapper:
 mappers: com.imooc.my.mapper.MyMapper
 not-empty: false
 identity: MYSQL

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 61558846
  hikari:
    connection-timeout: 30000
    minimum-idle: 5
    maximum-pool-size: 20
    auto-commit: true
    idle-timeout: 600000
    pool-name: DateSourceHikarCP
    max-lifetime: 1800000
    connection-test-query: SELECT 1
